#服务的端口号
server:
  port: 9001

spring:
  profiles:
    active: dev
    
  #datasource配置
  datasource:
    #url: jdbc:mysql://rm-wz9yx75264zry2u3lto.mysql.rds.aliyuncs.com:3306/ugaoxin_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    #username: root
    #password: KMB896#02
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://149.129.112.244:8066/mycat_db
    username: root
    password: KMB896#02
    driver-class-name: com.mysql.jdbc.Driver
  #rabbitmq:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: susion
    password: susion   
 
 
    
debug: true

test_reflush: false
